spring:
  profiles:
    include:
      - secret
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: spring
    key-store: classpath:saml/keystore.jks
    key-store-password: secret

logging:
  level:
    org.springframework.security.saml.metadata: DEBUG

security:
  saml2:
    metadata-url: <metadata-url>
    user:
      blocked: <empty user>
